name: 1.0.$(Rev:r)
variables:
  sln: 'src/MilestoneTG.NHibernate.Extensions.sln'
jobs:
  - job: 
    displayName: Build
    pool:
      name: 'Hosted Windows 2019 with VS2019'
    steps:
      - task: DotNetCoreCLI@2
        displayName: restore
        inputs:
          command: restore
          projects: $(sln)

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          arguments: -c debug --no-restore --logger trx --results-directory $(Agent.TempDirectory) -p:Altcover=true -p:AltCoverCobertura=$(Agent.TempDirectory)/coverage.xml -p:AltCoverPathFilter=test
          projects: 'test/**/*.csproj'
          publishTestResults: false
        continueOnError: true

      - task: PublishCodeCoverageResults@1
        displayName: Publish code coverage results
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(Agent.TempDirectory)/coverage.xml

      - task: PublishTestResults@2
        displayName: Publish test results
        inputs:
          failTaskOnFailedTests: true
          testResultsFiles: $(Agent.TempDirectory)/*.trx
          testResultsFormat: VSTest

      - task: MSBuild@1
        displayName: Build and package
        inputs:
          msbuildArguments: /t:pack /p:Version=$(Build.BuildNumber) /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
          configuration: release
          platform: any cpu
          solution: $(sln)

      - script: |
          choco install docfx -y
          docfx build
        displayName: Build docs
        workingDirectory: doc
        enabled: false
        
      - task: PublishBuildArtifacts@1
        displayName: Publish build artifacts
        inputs:
          ArtifactName: drop
          PathtoPublish:  $(Build.ArtifactStagingDirectory)

      - task: NuGetCommand@2
        displayName: Publish to Nuget.org
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'Milestonetg-NuGet'
